### ISSUE TITLE
VSCode debug mode

### ISSUE THREAD

**Issue by danyrouh** [jupyterlab/debug-config-cookiecutter#2]
## Description
I followed the steps to create the random picture extension example: https://jupyterlab.readthedocs.io/en/latest/extension/extension_tutorial.html#extension-tutorial 
Everything worked as published, but not the debug mode.  Every time  I tried to run the code in VSCode debug mode, it fails with some error related to the compatibility between ES and commons compiler. TypeScript configs should have handled this conversion but it still fails.

I tried every possible configs  I can find online, nothing worked.

I eventually found your template and installed it:  https://github.com/jupyterlab/debug-config-cookiecutter
It works, it runs, but still it does not break at any existing break point or step through the code line by line.
## Reproduce

Simply click F5

## Expected behavior

Should step through the code line by line, and stops at breakpoints.  

Can you share a working version of a JupyterLab extension VSCode project, so  I can compare it to mine and maybe find out what's wrong if any?

## Context

- Operating System and version: windows 10
- Browser and version: Edge latest version
- JupyterLab version: >=3.0.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by fcollonval** [comment]
Closing as the latest version works. Please open a new issue if it does not.
